[package]
name = "cardio-rs"
version = "0.1.0"
edition = "2024"

[features]
default = []
std = [
  "arrayvec/std",
  "num/std",
  "approx/std",
  "welch-sde",
  "rand/std",
  "rand_distr/std",
]

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
find_peaks = "0.1.5"
interp = "2.0.2"
libm = { version = "0.2.11", default-features = false }
num = { version = "0.4.3" }
polars = { version = "0.46.0", features = ["polars-io"] }
polars-lazy = { version = "0.46.0", features = ["csv", "diff"] }
welch-sde = { git = "https://github.com/bgallois/welch-sde.git", branch = "main", optional = true }

[dev-dependencies]
approx = { version = "0.5"}
rand = { version = "0.9", features = ["alloc"] }
rand_distr = { version = "0.5", features = ["alloc"] }
